'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class CallCentreMenu

    '''<summary>
    '''hldCallBookNav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hldCallBookNav As Global.Intuitive.WebControls.FrameHolder

    '''<summary>
    '''mnuBooking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuBooking As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BookingDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BookingDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''LeadGuest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LeadGuest As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BookingComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BookingComment As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Payment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Payment As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''AddLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''AddPackageLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddPackageLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuProperty As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PropertyBookingDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyBookingDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PropertyContractSelection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyContractSelection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PropertyRates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyRates As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PropertyGuestDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyGuestDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PropertyPackages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyPackages As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PropertyErrata control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyErrata As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PropertyBookingComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyBookingComments As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PropertyLinkedBookings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyLinkedBookings As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PropertyConfirmation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PropertyConfirmation As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mnuPackage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mnuPackage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PackageBookingDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PackageBookingDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PackageBookingComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PackageBookingComments As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''PackageLinkedBookings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PackageLinkedBookings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
